name: knock-knock
version: 1.0.5
title: Knock Knock
summary: Control a door remotely
description: |
  The Application is used to interact with doors via SSH in the local network.

  It provides following functions:
  * Searching for a door over IP in local network
  * Opening a door via custom SSH command
  * Closing a door via custom SSH command
  * Reading status of a door using SSH
contact:
  - jacki@thejackimonster.de
website:
  - https://gitlab.com/TheJackiMonster/knock-knock
source-code:
  - https://gitlab.com/TheJackiMonster/knock-knock/-/tree/main
issues:
  - https://gitlab.com/TheJackiMonster/knock-knock/-/issues
donation:
  - https://liberapay.com/TheJackiMonster
license: GPL-3.0+
adopt-info: knock-knock
icon: resources/de.thejackimonster.KnockKnock.svg
base: core24
confinement: strict
grade: stable

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

slots:
  knock-knock:
    interface: dbus
    bus: session
    name: de.thejackimonster.KnockKnock

apps:
  knock-knock:
    command: usr/share/knock-knock/door.sh
    extensions: [gnome]
    plugs:
      - home
      - network
      - network-bind
      - network-observe
    desktop: usr/share/applications/de.thejackimonster.KnockKnock.desktop
    common-id: de.thejackimonster.KnockKnock

parts:
  icmplib:
    plugin: python
    source: .
    python-packages:
      - icmplib

  knock-knock:
    plugin: dump
    after: [icmplib]
    source: https://gitlab.com/TheJackiMonster/knock-knock/-/archive/v1.0.5/knock-knock-v1.0.5.tar.gz
    source-checksum: sha256/98b79e62ba63d9fb2cc6b4587ee56ae3cfc6cae396860837041aed48873c48c6
    stage-packages:
      - iputils-ping
      - openssh-client
      - python3
      - desktop-file-utils
    override-prime: |
      cd $CRAFT_PART_INSTALL
      sh scripts/install.sh $CRAFT_PRIME/usr
